[workspace]
members = ["orchestrator", "cosmos_peggy", "ethereum_peggy", "peggy_utils", "proto_build", "test_runner", "peggy_proto", "relayer", "client", "register_delegate_keys","json_logger"]
default-members = ["orchestrator"]


[patch.crates-io]
